apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus2
  labels:
    app: quarkus2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus2
  template:
    spec:
      containers:
      - name: quarkus2
        image: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/quarkus2:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: quarkus2-configmap
    metadata:
      labels:
        app: quarkus2
